INSERT INTO groups (name) VALUES 
	('first'),
	('second'),
	('third'),
	('fourth'),
	('fifth'),
	('SR-01');

INSERT INTO students (group_id, first_name, last_name) VALUES
	(1,'JAMES', 'SMITH'),
	(1,'JOHN', 'JOHNSON'),
	(1,'ROBERT', 'WILLIAMS'),
	(1,'MICHAEL', 'BROWN'),
	(1,'WILLIAM', 'JONES'),
	(1,'WILLIAM', 'MILLER'),
	(1,'RICHARD', 'DAVIS'),
	(1,'CHARLES', 'GARCIA'),
	(1,'JOSEPH', 'RODRIGUEZ'),
	(1,'THOMAS', 'WILSON'),
	(1,'CHRISTOPHER', 'MARTINEZ'),
	(1,'DANIEL', 'ANDERSON'),
	(1,'PAUL', 'TAYLOR'),
	(1,'MARK', 'THOMAS'),
	(1,'DONALD', 'HERNANDEZ'),
	(1,'GEORGE', 'MOORE'),
	(1,'KENNETH', 'MARTIN'),
	(1,'STEVEN', 'JACKSON'),
	(2,'EDWARD', 'THOMPSON'),
	(2,'BRIAN', 'WHITE'),
	(2,'RONALD', 'LOPEZ'),
	(2,'ANTHONY', 'LEE'),
	(2,'KEVIN', 'GONZALEZ'),
	(2,'JASON', 'HARRIS'),
	(2,'MATTHEW', 'CLARK'),
	(2,'GARY', 'LEWIS'),
	(2,'TIMOTHY', 'ROBINSON'),
	(2,'JOSE', 'WALKER'),
	(2,'LARRY', 'PEREZ'),
	(2,'JEFFREY', 'HALL'),
	(2,'FRANK', 'YOUNG'),
	(2,'SCOTT', 'ALLEN'),
	(3,'ERIC', 'SANCHEZ'),
	(3,'STEPHEN', 'WRIGHT'),
	(3,'ANDREW', 'KING'),
	(3,'RAYMOND', 'SCOTT'),
	(3,'GREGORY', 'GREEN'),
	(3,'JOSHUA', 'BAKER'),
	(4,'JERRY', 'ADAMS'),
	(4,'DENNIS', 'NELSON'),
	(4,'WALTER', 'HILL'),
	(4,'PATRICK', 'RAMIREZ'),
	(4,'PETER', 'CAMPBELL'),
	(4,'HAROLD', 'MITCHELL'),
	(5,'DOUGLAS', 'ROBERTS'),
	(5,'HENRY', 'CARTER'),
	(5,'CARL', 'PHILLIPS'),
	(6,'ARTHUR','EVANS');


INSERT INTO courses (name, description) VALUES 
	('1 course', 'Junior'),
	('2 course', 'Middle'),
	('3 course', 'Senior');

INSERT INTO courses_students (course_id, student_id) VALUES 
	(1, 1),
	(1, 2),
	(1, 3),
	(1, 4),
	(1, 5),
	(1, 6),
	(1, 7),
	(1, 8),
	(1, 9),
	(1, 10),
	(1, 11),
	(1, 12),
	(1, 13),
	(1, 14),
	(1, 15),
	(1, 16),
	(1, 17),
	(1, 18),
	(1, 19),
	(1, 20),
	(1, 21),
	(1, 22),
	(1, 23),
	(1, 24),
	(1, 25),
	(1, 26),
	(1, 27),
	(1, 28),
	(1, 29),
	(1, 30),
	(1, 31),
	(2, 32),
	(2, 33),
	(2, 34),
	(2, 35),
	(2, 36),
	(2, 37),
	(2, 38),
	(2, 39),
	(2, 40),
	(2, 41),
	(2, 42),
	(3, 43),
	(3, 44),
	(3, 45),
	(3, 46),
	(3, 47),
	(3, 48);
 